// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/remoteworker/forwarded_request_header.proto

package remoteworker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardedRequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedRequestHeader) Reset() {
	*x = ForwardedRequestHeader{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedRequestHeader) ProtoMessage() {}

func (x *ForwardedRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedRequestHeader.ProtoReflect.Descriptor instead.
func (*ForwardedRequestHeader) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardedRequestHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForwardedRequestHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDesc = "" +
	"\n" +
	"^github.com/buildbarn/bb-remote-execution/pkg/proto/remoteworker/forwarded_request_header.proto\x12\x16buildbarn.remoteworker\"B\n" +
	"\x16ForwardedRequestHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueBAZ?github.com/buildbarn/bb-remote-execution/pkg/proto/remoteworkerb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_goTypes = []any{
	(*ForwardedRequestHeader)(nil), // 0: buildbarn.remoteworker.ForwardedRequestHeader
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteworker_forwarded_request_header_proto_depIdxs = nil
}
